### ISSUE TITLE
Country and Capital Card Template Update to Mimic Cloze

### ISSUE THREAD

**Issue by ohare93** [axelboc/anki-ultimate-geography#90]
Let me start by saying that perhaps this is just an issue I have faced.

I've always had an issue where I would misread "Capital" as "Country" and vice versa, when speeding through the cards. I would either spend a long time staring at the 'Capital' in complete bewilderment trying to work out it's supposed 'Country' before realising my mistake, or I would mistake similar looking/sounding Countries and Capitals like "Belarus" and "Belgrade" and give the wrong answer because of this. I was always annoyed by this because *I did genuinely know the answer* but I felt bad about this mistake and marking the answer as Good nonetheless.

So I changed my Card Templates to mimic a cloze deletion.

>Country -> Capital
![image](https://user-images.githubusercontent.com/1471350/56987052-b05d2a80-6b8c-11e9-91ae-35377036fb96.png)

>Capital -> Country
![image](https://user-images.githubusercontent.com/1471350/56987055-b3f0b180-6b8c-11e9-82da-94404cdaa079.png)

This way the Countries are always on the top and the capitals are always on the bottom. This got rid of this issue *immediately* and I believe it has helped my recall as a result. You can ignore the colours and size of "Country" and "Capital", as well as any cosmetic change I have made as a part of this. The style of a cloze deletion is all I am really advocating for. The "???" can also be changed to directly copy the style of a cloze "[...]" in blue.

##### Sidenote: the "Show Map" button is just made by the `{{#Map}}<br>{{hint:Map}}{{/Map}}` and I only rarely click it when I get a new card which I have never heard of, do not know the location, and am not getting the Map card today. Rather than clicking edit and looking at the map, which I used to do a lot (which is seemingly impossible in AnkiDroid). This helps better associate it in my mind with it's neighbours and learn faster.

**Comment by axelboc** [comment]
Ooh I quite like this. It keeps tripping me up too. The fact that the `COUNTRY` and `CAPITAL` headings kind of look the same doesn't help either...

Did you do the same for maps and flags -- i.e. put the country at the top? The difficulty with the _Country - Map_ template is that not all notes are countries (water bodies, continents, regions, etc.)

**Comment by ohare93** [comment]
###### I'm not the only one! 😄 

No I haven't changed the Flag and Map Card Type layouts yet. Though I imagine it would be beneficial to do so after I move onto the Extended version of the deck and get the reverse cards! 😅 As it stands I have 30% of the deck (and therefore *the world*) left to go, so I think I'll finish that first.

I think sometime in the coming weeks I will fork this repo and follow your steps on getting AnkiCrowd up and running. Been meaning to do so, but my structural changes of the card types and a worry of losing that has kept me from doing so.

**Comment by Erim24** [comment]
I think that that is a very helpful change that honestly could also help me to memorize some I had troubles with so far

**Comment by Erim24** [comment]
I noticed that for the Country>Capital cards the <hr> tag still has the id=answer.
I think that that should be removed if it will be added to the master as (if I remember correctly) might cause Anki to scroll down if not the whole card can be shown.
So far it shouldn't be a problem as I don't think there are cards with so much information on them. It might prevent some unintended behaviour in the future.

**Comment by axelboc** [comment]
I'm reluctant to change the standard deck, but I'm thinking this could actually be implemented as a new deck version, with its own cloze-style templates.

**Comment by ohare93** [comment]
I understand your concern, but then you would have to make a copy for each language, and the extended versions, both with and without this change. The number of decks would double!

Instead, how about trying out my template in your own deck for a while (anyone here, that is) and see how you like it? I think changing this over as the main method is a much more desirable position. Also, the only people who would ever see it are people who are new to the deck, or people such as ourselves who wish to get the most out of this, and would most likely be capable of reverting such a change.


Front Template
```html
{{#Capital}}
  <div class="country country--top">Country</div>
  <div class="value">{{Country}}</div>

  <hr id=answer>

  <div class="capital">Capital</div>
  <div class="value">???</div>
{{/Capital}}
```

Back Template
```html
{{#Capital}}
  <div class="country country--top">Country</div>
  <div class="value">{{Country}}</div>
  {{#Country info}}<div class="info">{{Country info}}</div>{{/Country info}}

  <hr id=answer>

  <div class="capital">Capital</div>
  <div class="value">{{Capital}}</div>
  {{#Capital hint}}<div class="info">{{Capital hint}}</div>{{/Capital hint}}
{{/Capital}}

{{#Capital info}}<div class="info">{{Capital info}}</div>{{/Capital info}}

{{#Map}}<br>{{hint:Map}}{{/Map}}
```

Styling
```css
.card {
  background-color: white;
  color: black;
  font-family: Verdana;
  font-size: 16px;
  padding: 1em 0;
  text-align: center;
}

.country {
  color: #BB0000;
  font-size: 90%;
  font-weight: bold;
  margin-bottom: .25em;
  text-transform: uppercase;
}

.nightMode .country {
  color: #BB0000;
}

.country--top {
  margin-top: 1em;
}

.capital {
  color: #0000BB;
  font-size: 60%;
  font-weight: bold;
  margin-bottom: .25em;
  text-transform: uppercase;
}

.nightMode .capital {
  color: #0000BB;
}

.capital--top {
  margin-top: 1em;
}

.value {
  font-size: 150%;
}

.mnemonic {
  font-size: 50%;
}

.nightMode .mnemonic {
 color: yellow;
}

.italic {
  font-style: italic;
}

.flag img {
  box-shadow: 3px 3px 3px rgba(0, 0, 0, .3);
}

.info {
  color: #333;
  font-size: 90%;
  font-style: italic;
  margin: .75em auto;
  max-width: 30em;
}

.info + .info {
  margin-top: -.375em;
}

.nightMode .info {
 color: yellow;
}

.hint{
  font-size: 30%
}

#answer {
  margin: 1.5em 0;
}

```
